version: '3.4'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: smn
    container_name: smn
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'RUNNER'
      # You can use whatever password you like
      # MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 10s
            retries: 10

# Names our volume
volumes:
  my-db: